name : main CI with backend

on:
  push:
    branches: [ main ]



jobs:
  ci:
    name: Backend CI
    runs-on: ubuntu-latest

    # 워크플로우 권한 정의
    permissions:
      contents: read
      id-token: write      # GCP Workload Identity와 통신하기 위한 OIDC 토큰 발행 권한

      
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v7
        
        
      # 2. JDK 환경 설정 (캐싱 포함)
      - name: Set up JDK 25
        uses: actions/setup-java@v6
        with:
          java-version: '25'
          distribution: 'temurin'
          
      # 3. Gradle 실행 권한 부여
      - name: Grant execute permission
        run: chmod +x gradlew
        
      # 4.Gradle 빌드 캐시
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      # Phase 1: Lint (Checkstyle)
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain

      # Phase 2: Compile
      - name: Run Compile 
        run: ./gradlew bootJar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v3

      # Docker가 GCP 인증 정보를 사용하도록 연결
      - name: Configure Docker authentication
        run: |
            cloud auth configure-docker "${{ secrets.GCP_REGION }}-docker.pkg.dev" --quiet

      # 이미지 빌드 + Artifact Registry 업로드
      - name: Build and push backend image
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.PROJECT_REPOSITORY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
